// Scans the public/icons/ directory and (re)generates src/items.ts with the item catalog.
// Run with: node scripts/generate-items.mjs
import { readdirSync, writeFileSync } from 'node:fs';
import { join, relative, extname, basename } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const PUBLIC_DIR = join(ROOT, 'public');
const ICONS_DIR = join(PUBLIC_DIR, 'icons');
const OUTPUT = join(ROOT, 'src', 'items.ts');

function cleanName(filename) {
  let name = filename.replace(/_/g, ' ');
  name = name.replace(/\s*\b(icon|new)\b\s*$/i, '');
  return name.trim();
}

function walk(dir, parts) {
  const entries = readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
  const items = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      items.push(...walk(full, [...parts, entry.name]));
    } else if (extname(entry.name).toLowerCase() === '.webp') {
      const baseName = basename(entry.name, extname(entry.name));
      // Path segments below icons/ become, in order: category, subcategory, group.
      // Files placed directly in icons/ fall back to a generic "Geral" category.
      const [category, subcategory, group] = parts.length ? parts : ['Geral'];
      const iconPath = relative(PUBLIC_DIR, full).split('\\').join('/');
      items.push({
        id: relative(ICONS_DIR, full).split('\\').join('/').replace(/\.webp$/i, ''),
        category,
        subcategory: subcategory ?? null,
        group: group ?? null,
        name: cleanName(baseName),
        icon: iconPath,
      });
    }
  }
  return items;
}

const items = walk(ICONS_DIR, []);

const header = `// AUTO-GENERATED by scripts/generate-items.mjs — do not edit by hand.
// Re-run "npm run generate-items" after adding/removing icons in public/icons/.
import type { Item } from './types';

`;

const body = `export const ITEM_CATALOG: Item[] = ${JSON.stringify(items, null, 2)};\n`;

writeFileSync(OUTPUT, header + body, 'utf8');
console.log(`Wrote ${items.length} items to ${relative(ROOT, OUTPUT)}`);
