// AUTO-GENERATED by scripts/generate-items.mjs — do not edit by hand.
// Re-run "npm run generate-items" after adding/removing icons in public/icons/.
import type { Item } from './types';

export const ITEM_CATALOG: Item[] = [
  {
    "id": "Equipment/Compass",
    "category": "Equipment",
    "subcategory": null,
    "group": null,
    "name": "Compass",
    "icon": "icons/Equipment/Compass.webp"
  },
  {
    "id": "Equipment/DAGR",
    "category": "Equipment",
    "subcategory": null,
    "group": null,
    "name": "DAGR",
    "icon": "icons/Equipment/DAGR.webp"
  },
  {
    "id": "Equipment/Keychain_NEW",
    "category": "Equipment",
    "subcategory": null,
    "group": null,
    "name": "Keychain",
    "icon": "icons/Equipment/Keychain_NEW.webp"
  },
  {
    "id": "Equipment/Lighter",
    "category": "Equipment",
    "subcategory": null,
    "group": null,
    "name": "Lighter",
    "icon": "icons/Equipment/Lighter.webp"
  },
  {
    "id": "Equipment/Map_NEW",
    "category": "Equipment",
    "subcategory": null,
    "group": null,
    "name": "Map",
    "icon": "icons/Equipment/Map_NEW.webp"
  },
  {
    "id": "Heals/Medical/AA-2_MedKit_29",
    "category": "Heals",
    "subcategory": "Medical",
    "group": null,
    "name": "AA-2 MedKit 29",
    "icon": "icons/Heals/Medical/AA-2_MedKit_29.webp"
  },
  {
    "id": "Heals/Medical/AI-4_cropped",
    "category": "Heals",
    "subcategory": "Medical",
    "group": null,
    "name": "AI-4 cropped",
    "icon": "icons/Heals/Medical/AI-4_cropped.webp"
  },
  {
    "id": "Heals/Medical/Bandage",
    "category": "Heals",
    "subcategory": "Medical",
    "group": null,
    "name": "Bandage",
    "icon": "icons/Heals/Medical/Bandage.webp"
  },
  {
    "id": "Heals/Medical/IFAK",
    "category": "Heals",
    "subcategory": "Medical",
    "group": null,
    "name": "IFAK",
    "icon": "icons/Heals/Medical/IFAK.webp"
  },
  {
    "id": "Heals/Medical/Individual_Medkit-2",
    "category": "Heals",
    "subcategory": "Medical",
    "group": null,
    "name": "Individual Medkit-2",
    "icon": "icons/Heals/Medical/Individual_Medkit-2.webp"
  },
  {
    "id": "Heals/Medical/Rag",
    "category": "Heals",
    "subcategory": "Medical",
    "group": null,
    "name": "Rag",
    "icon": "icons/Heals/Medical/Rag.webp"
  },
  {
    "id": "Heals/Medical/Wound_Dressing_2",
    "category": "Heals",
    "subcategory": "Medical",
    "group": null,
    "name": "Wound Dressing 2",
    "icon": "icons/Heals/Medical/Wound_Dressing_2.webp"
  },
  {
    "id": "Heals/Stims/Green_serum",
    "category": "Heals",
    "subcategory": "Stims",
    "group": null,
    "name": "Green serum",
    "icon": "icons/Heals/Stims/Green_serum.webp"
  },
  {
    "id": "Heals/Stims/Red_serum",
    "category": "Heals",
    "subcategory": "Stims",
    "group": null,
    "name": "Red serum",
    "icon": "icons/Heals/Stims/Red_serum.webp"
  },
  {
    "id": "Heals/Stims/Serum-x_P",
    "category": "Heals",
    "subcategory": "Stims",
    "group": null,
    "name": "Serum-x P",
    "icon": "icons/Heals/Stims/Serum-x_P.webp"
  },
  {
    "id": "Heals/Stims/Yellow_serum",
    "category": "Heals",
    "subcategory": "Stims",
    "group": null,
    "name": "Yellow serum",
    "icon": "icons/Heals/Stims/Yellow_serum.webp"
  },
  {
    "id": "Loot/Components/Fuze",
    "category": "Loot",
    "subcategory": "Components",
    "group": null,
    "name": "Fuze",
    "icon": "icons/Loot/Components/Fuze.webp"
  },
  {
    "id": "Loot/Components/Motor_Oil",
    "category": "Loot",
    "subcategory": "Components",
    "group": null,
    "name": "Motor Oil",
    "icon": "icons/Loot/Components/Motor_Oil.webp"
  },
  {
    "id": "Loot/Components/Weapon_Part",
    "category": "Loot",
    "subcategory": "Components",
    "group": null,
    "name": "Weapon Part",
    "icon": "icons/Loot/Components/Weapon_Part.webp"
  },
  {
    "id": "Loot/Electronics/AA_battery",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "AA battery",
    "icon": "icons/Loot/Electronics/AA_battery.webp"
  },
  {
    "id": "Loot/Electronics/Copper_coil",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "Copper coil",
    "icon": "icons/Loot/Electronics/Copper_coil.webp"
  },
  {
    "id": "Loot/Electronics/CPU_FAN",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "CPU FAN",
    "icon": "icons/Loot/Electronics/CPU_FAN.webp"
  },
  {
    "id": "Loot/Electronics/CPU",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "CPU",
    "icon": "icons/Loot/Electronics/CPU.webp"
  },
  {
    "id": "Loot/Electronics/GPU",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "GPU",
    "icon": "icons/Loot/Electronics/GPU.webp"
  },
  {
    "id": "Loot/Electronics/PSU",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "PSU",
    "icon": "icons/Loot/Electronics/PSU.webp"
  },
  {
    "id": "Loot/Electronics/RAM",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "RAM",
    "icon": "icons/Loot/Electronics/RAM.webp"
  },
  {
    "id": "Loot/Electronics/SMARTPHONE",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "SMARTPHONE",
    "icon": "icons/Loot/Electronics/SMARTPHONE.webp"
  },
  {
    "id": "Loot/Electronics/SSD",
    "category": "Loot",
    "subcategory": "Electronics",
    "group": null,
    "name": "SSD",
    "icon": "icons/Loot/Electronics/SSD.webp"
  },
  {
    "id": "Loot/Materials/Aramid",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Aramid",
    "icon": "icons/Loot/Materials/Aramid.webp"
  },
  {
    "id": "Loot/Materials/Cotton",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Cotton",
    "icon": "icons/Loot/Materials/Cotton.webp"
  },
  {
    "id": "Loot/Materials/DuctTape",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "DuctTape",
    "icon": "icons/Loot/Materials/DuctTape.webp"
  },
  {
    "id": "Loot/Materials/Gunpowder",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Gunpowder",
    "icon": "icons/Loot/Materials/Gunpowder.webp"
  },
  {
    "id": "Loot/Materials/Linen",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Linen",
    "icon": "icons/Loot/Materials/Linen.webp"
  },
  {
    "id": "Loot/Materials/Metal_Bolts",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Metal Bolts",
    "icon": "icons/Loot/Materials/Metal_Bolts.webp"
  },
  {
    "id": "Loot/Materials/Metal_Nails",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Metal Nails",
    "icon": "icons/Loot/Materials/Metal_Nails.webp"
  },
  {
    "id": "Loot/Materials/Metal_Nuts",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Metal Nuts",
    "icon": "icons/Loot/Materials/Metal_Nuts.webp"
  },
  {
    "id": "Loot/Materials/Metal",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Metal",
    "icon": "icons/Loot/Materials/Metal.webp"
  },
  {
    "id": "Loot/Materials/Ripstop",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Ripstop",
    "icon": "icons/Loot/Materials/Ripstop.webp"
  },
  {
    "id": "Loot/Materials/Steel_Pipe",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Steel Pipe",
    "icon": "icons/Loot/Materials/Steel_Pipe.webp"
  },
  {
    "id": "Loot/Materials/Superglue",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Superglue",
    "icon": "icons/Loot/Materials/Superglue.webp"
  },
  {
    "id": "Loot/Materials/Wooden_Planks",
    "category": "Loot",
    "subcategory": "Materials",
    "group": null,
    "name": "Wooden Planks",
    "icon": "icons/Loot/Materials/Wooden_Planks.webp"
  },
  {
    "id": "Loot/Tools/Flathead_screwdriver",
    "category": "Loot",
    "subcategory": "Tools",
    "group": null,
    "name": "Flathead screwdriver",
    "icon": "icons/Loot/Tools/Flathead_screwdriver.webp"
  },
  {
    "id": "Loot/Tools/Hammer",
    "category": "Loot",
    "subcategory": "Tools",
    "group": null,
    "name": "Hammer",
    "icon": "icons/Loot/Tools/Hammer.webp"
  },
  {
    "id": "Loot/Tools/Ph2_screwdriver",
    "category": "Loot",
    "subcategory": "Tools",
    "group": null,
    "name": "Ph2 screwdriver",
    "icon": "icons/Loot/Tools/Ph2_screwdriver.webp"
  },
  {
    "id": "Loot/Tools/RepairKit",
    "category": "Loot",
    "subcategory": "Tools",
    "group": null,
    "name": "RepairKit",
    "icon": "icons/Loot/Tools/RepairKit.webp"
  },
  {
    "id": "Loot/Tools/Wrench",
    "category": "Loot",
    "subcategory": "Tools",
    "group": null,
    "name": "Wrench",
    "icon": "icons/Loot/Tools/Wrench.webp"
  },
  {
    "id": "Loot/Valuables/50G_Of_Gold",
    "category": "Loot",
    "subcategory": "Valuables",
    "group": null,
    "name": "50G Of Gold",
    "icon": "icons/Loot/Valuables/50G_Of_Gold.webp"
  },
  {
    "id": "Loot/Valuables/Flare_nbg",
    "category": "Loot",
    "subcategory": "Valuables",
    "group": null,
    "name": "Flare nbg",
    "icon": "icons/Loot/Valuables/Flare_nbg.webp"
  },
  {
    "id": "Loot/Valuables/GOLD_TIX",
    "category": "Loot",
    "subcategory": "Valuables",
    "group": null,
    "name": "GOLD TIX",
    "icon": "icons/Loot/Valuables/GOLD_TIX.webp"
  },
  {
    "id": "Loot/Valuables/GOLD_WATCH",
    "category": "Loot",
    "subcategory": "Valuables",
    "group": null,
    "name": "GOLD WATCH",
    "icon": "icons/Loot/Valuables/GOLD_WATCH.webp"
  },
  {
    "id": "Loot/Valuables/SolterStatueReplica",
    "category": "Loot",
    "subcategory": "Valuables",
    "group": null,
    "name": "SolterStatueReplica",
    "icon": "icons/Loot/Valuables/SolterStatueReplica.webp"
  },
  {
    "id": "Loot/Valuables/SPS",
    "category": "Loot",
    "subcategory": "Valuables",
    "group": null,
    "name": "SPS",
    "icon": "icons/Loot/Valuables/SPS.webp"
  },
  {
    "id": "Loot/Valuables/SPSh-44_Icon",
    "category": "Loot",
    "subcategory": "Valuables",
    "group": null,
    "name": "SPSh-44",
    "icon": "icons/Loot/Valuables/SPSh-44_Icon.webp"
  },
  {
    "id": "Rations/Drinks/Bloxy_Cola",
    "category": "Rations",
    "subcategory": "Drinks",
    "group": null,
    "name": "Bloxy Cola",
    "icon": "icons/Rations/Drinks/Bloxy_Cola.webp"
  },
  {
    "id": "Rations/Drinks/Cat Frog",
    "category": "Rations",
    "subcategory": "Drinks",
    "group": null,
    "name": "Cat Frog",
    "icon": "icons/Rations/Drinks/Cat Frog.webp"
  },
  {
    "id": "Rations/Drinks/Immunster_Atomic_Winter",
    "category": "Rations",
    "subcategory": "Drinks",
    "group": null,
    "name": "Immunster Atomic Winter",
    "icon": "icons/Rations/Drinks/Immunster_Atomic_Winter.webp"
  },
  {
    "id": "Rations/Drinks/Immunster_Reactor 4",
    "category": "Rations",
    "subcategory": "Drinks",
    "group": null,
    "name": "Immunster Reactor 4",
    "icon": "icons/Rations/Drinks/Immunster_Reactor 4.webp"
  },
  {
    "id": "Rations/Drinks/Immunster",
    "category": "Rations",
    "subcategory": "Drinks",
    "group": null,
    "name": "Immunster",
    "icon": "icons/Rations/Drinks/Immunster.webp"
  },
  {
    "id": "Rations/Drinks/Kev_Kola",
    "category": "Rations",
    "subcategory": "Drinks",
    "group": null,
    "name": "Kev Kola",
    "icon": "icons/Rations/Drinks/Kev_Kola.webp"
  },
  {
    "id": "Rations/Drinks/Water_Bottle",
    "category": "Rations",
    "subcategory": "Drinks",
    "group": null,
    "name": "Water Bottle",
    "icon": "icons/Rations/Drinks/Water_Bottle.webp"
  },
  {
    "id": "Rations/Food/Bennys_Beans",
    "category": "Rations",
    "subcategory": "Food",
    "group": null,
    "name": "Bennys Beans",
    "icon": "icons/Rations/Food/Bennys_Beans.webp"
  },
  {
    "id": "Rations/Food/Max Energy",
    "category": "Rations",
    "subcategory": "Food",
    "group": null,
    "name": "Max Energy",
    "icon": "icons/Rations/Food/Max Energy.webp"
  },
  {
    "id": "Rations/Food/Moloko",
    "category": "Rations",
    "subcategory": "Food",
    "group": null,
    "name": "Moloko",
    "icon": "icons/Rations/Food/Moloko.webp"
  },
  {
    "id": "Rations/Food/Poku Bar",
    "category": "Rations",
    "subcategory": "Food",
    "group": null,
    "name": "Poku Bar",
    "icon": "icons/Rations/Food/Poku Bar.webp"
  },
  {
    "id": "Rubles",
    "category": "Geral",
    "subcategory": null,
    "group": null,
    "name": "Rubles",
    "icon": "icons/Rubles.webp"
  },
  {
    "id": "Weapons/Parts/Extras/AN-PEQ-15",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Extras",
    "name": "AN-PEQ-15",
    "icon": "icons/Weapons/Parts/Extras/AN-PEQ-15.webp"
  },
  {
    "id": "Weapons/Parts/Extras/Flashlight_Firefly",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Extras",
    "name": "Flashlight Firefly",
    "icon": "icons/Weapons/Parts/Extras/Flashlight_Firefly.webp"
  },
  {
    "id": "Weapons/Parts/Extras/Lazer_Pointer",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Extras",
    "name": "Lazer Pointer",
    "icon": "icons/Weapons/Parts/Extras/Lazer_Pointer.webp"
  },
  {
    "id": "Weapons/Parts/Front/Akmi_front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "Akmi front",
    "icon": "icons/Weapons/Parts/Front/Akmi_front.webp"
  },
  {
    "id": "Weapons/Parts/Front/Akmn_front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "Akmn front",
    "icon": "icons/Weapons/Parts/Front/Akmn_front.webp"
  },
  {
    "id": "Weapons/Parts/Front/AKMN_Tactical_Front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "AKMN Tactical Front",
    "icon": "icons/Weapons/Parts/Front/AKMN_Tactical_Front.webp"
  },
  {
    "id": "Weapons/Parts/Front/Fal_Front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "Fal Front",
    "icon": "icons/Weapons/Parts/Front/Fal_Front.webp"
  },
  {
    "id": "Weapons/Parts/Front/Fal_tactical_front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "Fal tactical front",
    "icon": "icons/Weapons/Parts/Front/Fal_tactical_front.webp"
  },
  {
    "id": "Weapons/Parts/Front/M4_front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "M4 front",
    "icon": "icons/Weapons/Parts/Front/M4_front.webp"
  },
  {
    "id": "Weapons/Parts/Front/MK12_front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "MK12 front",
    "icon": "icons/Weapons/Parts/Front/MK12_front.webp"
  },
  {
    "id": "Weapons/Parts/Front/SKS_front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "SKS front",
    "icon": "icons/Weapons/Parts/Front/SKS_front.webp"
  },
  {
    "id": "Weapons/Parts/Front/Sks_tactical_front",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Front",
    "name": "Sks tactical front",
    "icon": "icons/Weapons/Parts/Front/Sks_tactical_front.webp"
  },
  {
    "id": "Weapons/Parts/Handles/Akmi_handle",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Handles",
    "name": "Akmi handle",
    "icon": "icons/Weapons/Parts/Handles/Akmi_handle.webp"
  },
  {
    "id": "Weapons/Parts/Handles/Akmn_handle",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Handles",
    "name": "Akmn handle",
    "icon": "icons/Weapons/Parts/Handles/Akmn_handle.webp"
  },
  {
    "id": "Weapons/Parts/Handles/Fal_handle",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Handles",
    "name": "Fal handle",
    "icon": "icons/Weapons/Parts/Handles/Fal_handle.webp"
  },
  {
    "id": "Weapons/Parts/Handles/M4_handle",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Handles",
    "name": "M4 handle",
    "icon": "icons/Weapons/Parts/Handles/M4_handle.webp"
  },
  {
    "id": "Weapons/Parts/Handles/Rk3_handle",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Handles",
    "name": "Rk3 handle",
    "icon": "icons/Weapons/Parts/Handles/Rk3_handle.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/20rnd_svd_mag",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "20rnd svd mag",
    "icon": "icons/Weapons/Parts/Magazines/20rnd_svd_mag.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/5.56x45_M4A1_100-Round_Drum",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "5.56x45 M4A1 100-Round Drum",
    "icon": "icons/Weapons/Parts/Magazines/5.56x45_M4A1_100-Round_Drum.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/7.62x25_PPSh-41_71-Round_Drum",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "7.62x25 PPSh-41 71-Round Drum",
    "icon": "icons/Weapons/Parts/Magazines/7.62x25_PPSh-41_71-Round_Drum.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/7.62x39_AKM_75-Round_Drum",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "7.62x39 AKM 75-Round Drum",
    "icon": "icons/Weapons/Parts/Magazines/7.62x39_AKM_75-Round_Drum.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/9x18_Pistol_Makarov_80-Round_Drum",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "9x18 Pistol Makarov 80-Round Drum",
    "icon": "icons/Weapons/Parts/Magazines/9x18_Pistol_Makarov_80-Round_Drum.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/9x19_MP5SD_50-Round_Drum",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "9x19 MP5SD 50-Round Drum",
    "icon": "icons/Weapons/Parts/Magazines/9x19_MP5SD_50-Round_Drum.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/9x39_AS_Val_30-Round_Magazine",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "9x39 AS Val 30-Round Magazine",
    "icon": "icons/Weapons/Parts/Magazines/9x39_AS_Val_30-Round_Magazine.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/PKMBOX",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "PKMBOX",
    "icon": "icons/Weapons/Parts/Magazines/PKMBOX.webp"
  },
  {
    "id": "Weapons/Parts/Magazines/Saiga_20_Round_Mag",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Magazines",
    "name": "Saiga 20 Round Mag",
    "icon": "icons/Weapons/Parts/Magazines/Saiga_20_Round_Mag.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/AKM_Muzzle_Brake",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "AKM Muzzle Brake",
    "icon": "icons/Weapons/Parts/Muzzle/AKM_Muzzle_Brake.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/KAC",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "KAC",
    "icon": "icons/Weapons/Parts/Muzzle/KAC.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/M4_Flash_Hider",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "M4 Flash Hider",
    "icon": "icons/Weapons/Parts/Muzzle/M4_Flash_Hider.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/Oil_Can_Supressor",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "Oil Can Supressor",
    "icon": "icons/Weapons/Parts/Muzzle/Oil_Can_Supressor.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/PBS1_Suppressor",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "PBS1 Suppressor",
    "icon": "icons/Weapons/Parts/Muzzle/PBS1_Suppressor.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/SOCOM556_RC2_Suppressor",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "SOCOM556 RC2 Suppressor",
    "icon": "icons/Weapons/Parts/Muzzle/SOCOM556_RC2_Suppressor.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/SVD_Flash_Hider",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "SVD Flash Hider",
    "icon": "icons/Weapons/Parts/Muzzle/SVD_Flash_Hider.webp"
  },
  {
    "id": "Weapons/Parts/Muzzle/TWS",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Muzzle",
    "name": "TWS",
    "icon": "icons/Weapons/Parts/Muzzle/TWS.webp"
  },
  {
    "id": "Weapons/Parts/Optics/ACOG",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "ACOG",
    "icon": "icons/Weapons/Parts/Optics/ACOG.webp"
  },
  {
    "id": "Weapons/Parts/Optics/Holographic_Sight.",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "Holographic Sight.",
    "icon": "icons/Weapons/Parts/Optics/Holographic_Sight..webp"
  },
  {
    "id": "Weapons/Parts/Optics/LVPO",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "LVPO",
    "icon": "icons/Weapons/Parts/Optics/LVPO.webp"
  },
  {
    "id": "Weapons/Parts/Optics/OKP-7",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "OKP-7",
    "icon": "icons/Weapons/Parts/Optics/OKP-7.webp"
  },
  {
    "id": "Weapons/Parts/Optics/PN6K-5_Night_Vision",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "PN6K-5 Night Vision",
    "icon": "icons/Weapons/Parts/Optics/PN6K-5_Night_Vision.webp"
  },
  {
    "id": "Weapons/Parts/Optics/PSO-1",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "PSO-1",
    "icon": "icons/Weapons/Parts/Optics/PSO-1.webp"
  },
  {
    "id": "Weapons/Parts/Optics/Pu_3.5x",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "Pu 3.5x",
    "icon": "icons/Weapons/Parts/Optics/Pu_3.5x.webp"
  },
  {
    "id": "Weapons/Parts/Optics/Reap-IR 35",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "Reap-IR 35",
    "icon": "icons/Weapons/Parts/Optics/Reap-IR 35.webp"
  },
  {
    "id": "Weapons/Parts/Optics/Rifle_Scope",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "Rifle Scope",
    "icon": "icons/Weapons/Parts/Optics/Rifle_Scope.webp"
  },
  {
    "id": "Weapons/Parts/Optics/Sniper_Scope",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "Sniper Scope",
    "icon": "icons/Weapons/Parts/Optics/Sniper_Scope.webp"
  },
  {
    "id": "Weapons/Parts/Optics/T1_Micro_Red_Dot_Sight",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "T1 Micro Red Dot Sight",
    "icon": "icons/Weapons/Parts/Optics/T1_Micro_Red_Dot_Sight.webp"
  },
  {
    "id": "Weapons/Parts/Optics/T12W",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Optics",
    "name": "T12W",
    "icon": "icons/Weapons/Parts/Optics/T12W.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/Akmi_stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "Akmi stock",
    "icon": "icons/Weapons/Parts/Stocks/Akmi_stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/Akmn_stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "Akmn stock",
    "icon": "icons/Weapons/Parts/Stocks/Akmn_stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/Fal_Polymer_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "Fal Polymer Stock",
    "icon": "icons/Weapons/Parts/Stocks/Fal_Polymer_Stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/Fal_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "Fal Stock",
    "icon": "icons/Weapons/Parts/Stocks/Fal_Stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/IZh81_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "IZh81 Stock",
    "icon": "icons/Weapons/Parts/Stocks/IZh81_Stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/M4_mk12",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "M4 mk12",
    "icon": "icons/Weapons/Parts/Stocks/M4_mk12.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/M4_stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "M4 stock",
    "icon": "icons/Weapons/Parts/Stocks/M4_stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/Mosin_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "Mosin Stock",
    "icon": "icons/Weapons/Parts/Stocks/Mosin_Stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/Polymer_akm",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "Polymer akm",
    "icon": "icons/Weapons/Parts/Stocks/Polymer_akm.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/PPSH-41_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "PPSH-41 Stock",
    "icon": "icons/Weapons/Parts/Stocks/PPSH-41_Stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/PT-1_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "PT-1 Stock",
    "icon": "icons/Weapons/Parts/Stocks/PT-1_Stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/SKS_Tactical_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "SKS Tactical Stock",
    "icon": "icons/Weapons/Parts/Stocks/SKS_Tactical_Stock.webp"
  },
  {
    "id": "Weapons/Parts/Stocks/SVD_Stock",
    "category": "Weapons",
    "subcategory": "Parts",
    "group": "Stocks",
    "name": "SVD Stock",
    "icon": "icons/Weapons/Parts/Stocks/SVD_Stock.webp"
  },
  {
    "id": "Weapons/Primary/ADAR15_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "ADAR15",
    "icon": "icons/Weapons/Primary/ADAR15_Icon.webp"
  },
  {
    "id": "Weapons/Primary/AKM-I_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "AKM-I",
    "icon": "icons/Weapons/Primary/AKM-I_Icon.webp"
  },
  {
    "id": "Weapons/Primary/AKMN_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "AKMN",
    "icon": "icons/Weapons/Primary/AKMN_Icon.webp"
  },
  {
    "id": "Weapons/Primary/AS_Val_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "AS Val",
    "icon": "icons/Weapons/Primary/AS_Val_Icon.webp"
  },
  {
    "id": "Weapons/Primary/FN_FAL_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "FN FAL",
    "icon": "icons/Weapons/Primary/FN_FAL_Icon.webp"
  },
  {
    "id": "Weapons/Primary/IZh-12_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "IZh-12",
    "icon": "icons/Weapons/Primary/IZh-12_Icon.webp"
  },
  {
    "id": "Weapons/Primary/IZh-81_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "IZh-81",
    "icon": "icons/Weapons/Primary/IZh-81_Icon.webp"
  },
  {
    "id": "Weapons/Primary/M4A1_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "M4A1",
    "icon": "icons/Weapons/Primary/M4A1_Icon.webp"
  },
  {
    "id": "Weapons/Primary/Mosin_Nagant_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "Mosin Nagant",
    "icon": "icons/Weapons/Primary/Mosin_Nagant_Icon.webp"
  },
  {
    "id": "Weapons/Primary/MP5SD_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "MP5SD",
    "icon": "icons/Weapons/Primary/MP5SD_Icon.webp"
  },
  {
    "id": "Weapons/Primary/PKM_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "PKM",
    "icon": "icons/Weapons/Primary/PKM_Icon.webp"
  },
  {
    "id": "Weapons/Primary/PPSH-41_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "PPSH-41",
    "icon": "icons/Weapons/Primary/PPSH-41_Icon.webp"
  },
  {
    "id": "Weapons/Primary/R700_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "R700",
    "icon": "icons/Weapons/Primary/R700_Icon.webp"
  },
  {
    "id": "Weapons/Primary/RPG-7_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "RPG-7",
    "icon": "icons/Weapons/Primary/RPG-7_Icon.webp"
  },
  {
    "id": "Weapons/Primary/Saiga_12_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "Saiga 12",
    "icon": "icons/Weapons/Primary/Saiga_12_Icon.webp"
  },
  {
    "id": "Weapons/Primary/SKS_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "SKS",
    "icon": "icons/Weapons/Primary/SKS_Icon.webp"
  },
  {
    "id": "Weapons/Primary/SVD_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "SVD",
    "icon": "icons/Weapons/Primary/SVD_Icon.webp"
  },
  {
    "id": "Weapons/Primary/TFZ-98S_Icon",
    "category": "Weapons",
    "subcategory": "Primary",
    "group": null,
    "name": "TFZ-98S",
    "icon": "icons/Weapons/Primary/TFZ-98S_Icon.webp"
  },
  {
    "id": "Weapons/Secondary/Golden_Makarov-1",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "Golden Makarov-1",
    "icon": "icons/Weapons/Secondary/Golden_Makarov-1.webp"
  },
  {
    "id": "Weapons/Secondary/MK23_Icon",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "MK23",
    "icon": "icons/Weapons/Secondary/MK23_Icon.webp"
  },
  {
    "id": "Weapons/Secondary/MP443_Icon",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "MP443",
    "icon": "icons/Weapons/Secondary/MP443_Icon.webp"
  },
  {
    "id": "Weapons/Secondary/PM_Icon",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "PM",
    "icon": "icons/Weapons/Secondary/PM_Icon.webp"
  },
  {
    "id": "Weapons/Secondary/Skorpion_Icon",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "Skorpion",
    "icon": "icons/Weapons/Secondary/Skorpion_Icon.webp"
  },
  {
    "id": "Weapons/Secondary/Temp_toz_pic_2",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "Temp toz pic 2",
    "icon": "icons/Weapons/Secondary/Temp_toz_pic_2.webp"
  },
  {
    "id": "Weapons/Secondary/TFZ-0_Icon",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "TFZ-0",
    "icon": "icons/Weapons/Secondary/TFZ-0_Icon.webp"
  },
  {
    "id": "Weapons/Secondary/TT-33_Icon",
    "category": "Weapons",
    "subcategory": "Secondary",
    "group": null,
    "name": "TT-33",
    "icon": "icons/Weapons/Secondary/TT-33_Icon.webp"
  },
  {
    "id": "Weapons/Throwables/F1_Grenade",
    "category": "Weapons",
    "subcategory": "Throwables",
    "group": null,
    "name": "F1 Grenade",
    "icon": "icons/Weapons/Throwables/F1_Grenade.webp"
  },
  {
    "id": "Weapons/Throwables/M84",
    "category": "Weapons",
    "subcategory": "Throwables",
    "group": null,
    "name": "M84",
    "icon": "icons/Weapons/Throwables/M84.webp"
  },
  {
    "id": "Weapons/Throwables/RGD5",
    "category": "Weapons",
    "subcategory": "Throwables",
    "group": null,
    "name": "RGD5",
    "icon": "icons/Weapons/Throwables/RGD5.webp"
  },
  {
    "id": "Weapons/Throwables/RGO",
    "category": "Weapons",
    "subcategory": "Throwables",
    "group": null,
    "name": "RGO",
    "icon": "icons/Weapons/Throwables/RGO.webp"
  },
  {
    "id": "Wearables/Backpacks/One-Strap_Backpack_Lynx_10L",
    "category": "Wearables",
    "subcategory": "Backpacks",
    "group": null,
    "name": "One-Strap Backpack Lynx 10L",
    "icon": "icons/Wearables/Backpacks/One-Strap_Backpack_Lynx_10L.webp"
  },
  {
    "id": "Wearables/Backpacks/Raid_Backpack_Attak-5_60L",
    "category": "Wearables",
    "subcategory": "Backpacks",
    "group": null,
    "name": "Raid Backpack Attak-5 60L",
    "icon": "icons/Wearables/Backpacks/Raid_Backpack_Attak-5_60L.webp"
  },
  {
    "id": "Wearables/Backpacks/Special_Operation_Backpack_30L",
    "category": "Wearables",
    "subcategory": "Backpacks",
    "group": null,
    "name": "Special Operation Backpack 30L",
    "icon": "icons/Wearables/Backpacks/Special_Operation_Backpack_30L.webp"
  },
  {
    "id": "Wearables/Backpacks/Tortilla_Backpack_45L",
    "category": "Wearables",
    "subcategory": "Backpacks",
    "group": null,
    "name": "Tortilla Backpack 45L",
    "icon": "icons/Wearables/Backpacks/Tortilla_Backpack_45L.webp"
  },
  {
    "id": "Wearables/Backpacks/Wasteland_Backpack",
    "category": "Wearables",
    "subcategory": "Backpacks",
    "group": null,
    "name": "Wasteland Backpack",
    "icon": "icons/Wearables/Backpacks/Wasteland_Backpack.webp"
  },
  {
    "id": "Wearables/Chest Rigs/6B2",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "6B2",
    "icon": "icons/Wearables/Chest Rigs/6B2.webp"
  },
  {
    "id": "Wearables/Chest Rigs/6B23",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "6B23",
    "icon": "icons/Wearables/Chest Rigs/6B23.webp"
  },
  {
    "id": "Wearables/Chest Rigs/6B45",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "6B45",
    "icon": "icons/Wearables/Chest Rigs/6B45.webp"
  },
  {
    "id": "Wearables/Chest Rigs/6B5",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "6B5",
    "icon": "icons/Wearables/Chest Rigs/6B5.webp"
  },
  {
    "id": "Wearables/Chest Rigs/Bandoiler",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "Bandoiler",
    "icon": "icons/Wearables/Chest Rigs/Bandoiler.webp"
  },
  {
    "id": "Wearables/Chest Rigs/Bulldozer_Armor",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "Bulldozer Armor",
    "icon": "icons/Wearables/Chest Rigs/Bulldozer_Armor.webp"
  },
  {
    "id": "Wearables/Chest Rigs/Chestplate",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "Chestplate",
    "icon": "icons/Wearables/Chest Rigs/Chestplate.webp"
  },
  {
    "id": "Wearables/Chest Rigs/Concealed_vest",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "Concealed vest",
    "icon": "icons/Wearables/Chest Rigs/Concealed_vest.webp"
  },
  {
    "id": "Wearables/Chest Rigs/GEN 4",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "GEN 4",
    "icon": "icons/Wearables/Chest Rigs/GEN 4.webp"
  },
  {
    "id": "Wearables/Chest Rigs/HSPV",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "HSPV",
    "icon": "icons/Wearables/Chest Rigs/HSPV.webp"
  },
  {
    "id": "Wearables/Chest Rigs/JPC",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "JPC",
    "icon": "icons/Wearables/Chest Rigs/JPC.webp"
  },
  {
    "id": "Wearables/Chest Rigs/Kulon_Vest",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "Kulon Vest",
    "icon": "icons/Wearables/Chest Rigs/Kulon_Vest.webp"
  },
  {
    "id": "Wearables/Chest Rigs/Recon",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "Recon",
    "icon": "icons/Wearables/Chest Rigs/Recon.webp"
  },
  {
    "id": "Wearables/Chest Rigs/UNO_Vest",
    "category": "Wearables",
    "subcategory": "Chest Rigs",
    "group": null,
    "name": "UNO Vest",
    "icon": "icons/Wearables/Chest Rigs/UNO_Vest.webp"
  },
  {
    "id": "Wearables/Gloves/Combat_Gloves",
    "category": "Wearables",
    "subcategory": "Gloves",
    "group": null,
    "name": "Combat Gloves",
    "icon": "icons/Wearables/Gloves/Combat_Gloves.webp"
  },
  {
    "id": "Wearables/Gloves/Hand_Wraps",
    "category": "Wearables",
    "subcategory": "Gloves",
    "group": null,
    "name": "Hand Wraps",
    "icon": "icons/Wearables/Gloves/Hand_Wraps.webp"
  },
  {
    "id": "Wearables/Helmets/6B27_Aramid_Helmet",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "6B27 Aramid Helmet",
    "icon": "icons/Wearables/Helmets/6B27_Aramid_Helmet.webp"
  },
  {
    "id": "Wearables/Helmets/6B47_Helmet",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "6B47 Helmet",
    "icon": "icons/Wearables/Helmets/6B47_Helmet.webp"
  },
  {
    "id": "Wearables/Helmets/Altyn_Helmet",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "Altyn Helmet",
    "icon": "icons/Wearables/Helmets/Altyn_Helmet.webp"
  },
  {
    "id": "Wearables/Helmets/Fast_MT_Helme",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "Fast MT Helme",
    "icon": "icons/Wearables/Helmets/Fast_MT_Helme.webp"
  },
  {
    "id": "Wearables/Helmets/Head_Mount",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "Head Mount",
    "icon": "icons/Wearables/Helmets/Head_Mount.webp"
  },
  {
    "id": "Wearables/Helmets/Motorcycle_Helmet",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "Motorcycle Helmet",
    "icon": "icons/Wearables/Helmets/Motorcycle_Helmet.webp"
  },
  {
    "id": "Wearables/Helmets/ScavCrown",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "ScavCrown",
    "icon": "icons/Wearables/Helmets/ScavCrown.webp"
  },
  {
    "id": "Wearables/Helmets/SSH-68",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "SSH-68",
    "icon": "icons/Wearables/Helmets/SSH-68.webp"
  },
  {
    "id": "Wearables/Helmets/TankerCap",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "TankerCap",
    "icon": "icons/Wearables/Helmets/TankerCap.webp"
  },
  {
    "id": "Wearables/Helmets/TOR-S_Helmet",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "TOR-S Helmet",
    "icon": "icons/Wearables/Helmets/TOR-S_Helmet.webp"
  },
  {
    "id": "Wearables/Helmets/Uno_helmet3",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "Uno helmet3",
    "icon": "icons/Wearables/Helmets/Uno_helmet3.webp"
  },
  {
    "id": "Wearables/Helmets/ZSh-1-2M_Helmet",
    "category": "Wearables",
    "subcategory": "Helmets",
    "group": null,
    "name": "ZSh-1-2M Helmet",
    "icon": "icons/Wearables/Helmets/ZSh-1-2M_Helmet.webp"
  },
  {
    "id": "Wearables/Leg Armor/Knee_Pads",
    "category": "Wearables",
    "subcategory": "Leg Armor",
    "group": null,
    "name": "Knee Pads",
    "icon": "icons/Wearables/Leg Armor/Knee_Pads.webp"
  },
  {
    "id": "Wearables/Leg Armor/Leg_armor",
    "category": "Wearables",
    "subcategory": "Leg Armor",
    "group": null,
    "name": "Leg armor",
    "icon": "icons/Wearables/Leg Armor/Leg_armor.webp"
  },
  {
    "id": "Wearables/Masks/Balaclava",
    "category": "Wearables",
    "subcategory": "Masks",
    "group": null,
    "name": "Balaclava",
    "icon": "icons/Wearables/Masks/Balaclava.webp"
  },
  {
    "id": "Wearables/Masks/Ghillie_Suit_Hood",
    "category": "Wearables",
    "subcategory": "Masks",
    "group": null,
    "name": "Ghillie Suit Hood",
    "icon": "icons/Wearables/Masks/Ghillie_Suit_Hood.webp"
  },
  {
    "id": "Wearables/Masks/GP5_filter",
    "category": "Wearables",
    "subcategory": "Masks",
    "group": null,
    "name": "GP5 filter",
    "icon": "icons/Wearables/Masks/GP5_filter.webp"
  },
  {
    "id": "Wearables/Masks/GP5",
    "category": "Wearables",
    "subcategory": "Masks",
    "group": null,
    "name": "GP5",
    "icon": "icons/Wearables/Masks/GP5.webp"
  },
  {
    "id": "Wearables/Pants/Camo_Pants",
    "category": "Wearables",
    "subcategory": "Pants",
    "group": null,
    "name": "Camo Pants",
    "icon": "icons/Wearables/Pants/Camo_Pants.webp"
  },
  {
    "id": "Wearables/Pants/Ghillie_Suit_Pants",
    "category": "Wearables",
    "subcategory": "Pants",
    "group": null,
    "name": "Ghillie Suit Pants",
    "icon": "icons/Wearables/Pants/Ghillie_Suit_Pants.webp"
  },
  {
    "id": "Wearables/Pants/Gorka_Pants",
    "category": "Wearables",
    "subcategory": "Pants",
    "group": null,
    "name": "Gorka Pants",
    "icon": "icons/Wearables/Pants/Gorka_Pants.webp"
  },
  {
    "id": "Wearables/Pants/Suit_Pants",
    "category": "Wearables",
    "subcategory": "Pants",
    "group": null,
    "name": "Suit Pants",
    "icon": "icons/Wearables/Pants/Suit_Pants.webp"
  },
  {
    "id": "Wearables/Shirts/Camo_Shirt",
    "category": "Wearables",
    "subcategory": "Shirts",
    "group": null,
    "name": "Camo Shirt",
    "icon": "icons/Wearables/Shirts/Camo_Shirt.webp"
  },
  {
    "id": "Wearables/Shirts/Ghillie_Suit_Shirt",
    "category": "Wearables",
    "subcategory": "Shirts",
    "group": null,
    "name": "Ghillie Suit Shirt",
    "icon": "icons/Wearables/Shirts/Ghillie_Suit_Shirt.webp"
  },
  {
    "id": "Wearables/Shirts/Gorka_Shirt",
    "category": "Wearables",
    "subcategory": "Shirts",
    "group": null,
    "name": "Gorka Shirt",
    "icon": "icons/Wearables/Shirts/Gorka_Shirt.webp"
  },
  {
    "id": "Wearables/Shirts/Suit_Shirt",
    "category": "Wearables",
    "subcategory": "Shirts",
    "group": null,
    "name": "Suit Shirt",
    "icon": "icons/Wearables/Shirts/Suit_Shirt.webp"
  },
  {
    "id": "Wearables/Visors/Atlyn_Visor",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "Atlyn Visor",
    "icon": "icons/Wearables/Visors/Atlyn_Visor.webp"
  },
  {
    "id": "Wearables/Visors/Fast_MT_Helmet_Visor",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "Fast MT Helmet Visor",
    "icon": "icons/Wearables/Visors/Fast_MT_Helmet_Visor.webp"
  },
  {
    "id": "Wearables/Visors/LowCutVisor",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "LowCutVisor",
    "icon": "icons/Wearables/Visors/LowCutVisor.webp"
  },
  {
    "id": "Wearables/Visors/Maska_visor",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "Maska visor",
    "icon": "icons/Wearables/Visors/Maska_visor.webp"
  },
  {
    "id": "Wearables/Visors/Motorcycle_Helmet_Visor",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "Motorcycle Helmet Visor",
    "icon": "icons/Wearables/Visors/Motorcycle_Helmet_Visor.webp"
  },
  {
    "id": "Wearables/Visors/Night_Vision_Goggles_9",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "Night Vision Goggles 9",
    "icon": "icons/Wearables/Visors/Night_Vision_Goggles_9.webp"
  },
  {
    "id": "Wearables/Visors/Quad_Night_Vision_Goggles",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "Quad Night Vision Goggles",
    "icon": "icons/Wearables/Visors/Quad_Night_Vision_Goggles.webp"
  },
  {
    "id": "Wearables/Visors/Spartan_Tech_Titan_Shield",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "Spartan Tech Titan Shield",
    "icon": "icons/Wearables/Visors/Spartan_Tech_Titan_Shield.webp"
  },
  {
    "id": "Wearables/Visors/ZSh-1-2M_Visor",
    "category": "Wearables",
    "subcategory": "Visors",
    "group": null,
    "name": "ZSh-1-2M Visor",
    "icon": "icons/Wearables/Visors/ZSh-1-2M_Visor.webp"
  }
];
